export const AUTH = {
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    SUCCESS: 'AUTH_SUCCESS',
    FAILURE: 'AUTH_FAILURE'
}

export const CONNECTION = {
    NEXT_STAGE: 'NEXT_STAGE',
    PREV_STAGE: 'PREV_STAGE',
    TO_STAGE: 'TO_STAGE',
    FROM_STAGE: 'FROM_STAGE',
    SUBSCRIBER_TYPE: 'SUBSCRIBER_TYPE',
    CONNECTION_TYPE: 'CONNECTION_TYPE'
}

export const STAGE = {
    TO: 'TO',
    FROM: 'FROM',
    CURRENT: 'CURRENT',
    INITIAL: 'INITIAL'
}